version: "3.8"
services:
  postgress: 
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - 5432:5432
    volumes:
      - ../postgres-ploty:/var/lib/postgresql/data

